### ISSUE TITLE
Can't download dataset

### ISSUE THREAD

**Issue by dhonza** [sheffieldnlp/naacl2018-fever#57]
Hi,
I am getting 403 errors when trying to download the dataset:

```bash
(base) drchajan@login1:~/devel/python/FC/THIRDPARTY/fever/fever-baselines$ wget -O data/fever-data/train.jsonl https://s3-eu-west-1.amazonaws.com/fever.public/train.jsonl
--2022-07-18 16:46:00--  https://s3-eu-west-1.amazonaws.com/fever.public/train.jsonl
Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 52.218.93.163
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|52.218.93.163|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-07-18 16:46:00 ERROR 403: Forbidden.
```

Was it moved elsewhere?
Best

Honza

**Comment by andreasvlachos** [comment]
Yes, see here:
https://fever.ai/

Cheers,
Andreas
________________________________
From: Jan Drchal ***@***.***>
Sent: 18 July 2022 15:50
To: sheffieldnlp/naacl2018-fever ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sheffieldnlp/naacl2018-fever] Can't download dataset (Issue #57)


Hi,
I am getting 403 errors when trying to download the dataset:

(base) ***@***.***:~/devel/python/FC/THIRDPARTY/fever/fever-baselines$ wget -O data/fever-data/train.jsonl https://s3-eu-west-1.amazonaws.com/fever.public/train.jsonl
--2022-07-18 16:46:00--  https://s3-eu-west-1.amazonaws.com/fever.public/train.jsonl
Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 52.218.93.163
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|52.218.93.163|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-07-18 16:46:00 ERROR 403: Forbidden.

Was it moved elsewhere?
Best

Honza
