### ISSUE TITLE
Can't download pretrained model

### ISSUE THREAD

**Issue by RuochenZhao** [sheffieldnlp/naacl2018-fever#58]
When I tried to run: bash scripts/download-model.sh

I got:
--2022-12-28 12:17:47--  https://s3-eu-west-1.amazonaws.com/fever.public/model.tar.gz
Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 52.92.1.168, 52.92.32.32, 52.218.92.35, ...
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|52.92.1.168|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-12-28 12:17:48 ERROR 403: Forbidden.

**Comment by RuochenZhao** [comment]
Same thing happens with the tokenizer and fever.db:

output:

Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 52.218.85.10, 52.218.0.11, 52.92.19.160, ...
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|52.218.85.10|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-12-28 12:35:22 ERROR 403: Forbidden.

**Comment by ernlavr** [comment]
Same here!
What happened? Did they decided to take the baseline off?

**Comment by ernlavr** [comment]
See https://fever.ai/
`
Download URLs for shared task data for FEVER, FEVER2.0 and FEVEROUS have been updated. New URLS begin with https://fever.ai/download/[task name]/[filename]. All resource pages have been updated with the new URLs. Previous dataset URLs may not work and should be updated if you require these in your scripts. 
`

**Comment by j6mes** [comment]
The models can be checked her. The files are updated with the info as given by @ernlavr. i will update the scripts

* https://jamesthorne.com/content/files/fever-da.tar.gz
* https://jamesthorne.com/content/files/fever-esim.tar.gz
